# Generated by Django 5.2.4 on 2025-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
                ('requirements', models.TextField()),
                ('eligibility', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('application_deadline', models.DateField()),
                ('max_positions', models.PositiveIntegerField(default=1)),
                ('current_accepted', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills_required', models.ManyToManyField(blank=True, to='internships.skill')),
            ],
        ),
    ]
