# Generated by Django 5.2.4 on 2025-10-24 05:05

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to=users.models.upload_to_cert, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to_profile_pic, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), users.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.upload_to_resume, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), users.models.validate_file_size]),
        ),
    ]
