# Generated by Django 5.2.4 on 2025-07-17 19:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('working', 'Working'), ('rejected', 'Rejected'), ('offer_expired', 'Offer Expired'), ('auto_rejected', 'Auto Rejected')], default='applied', max_length=20)),
                ('offer_made_at', models.DateTimeField(blank=True, null=True)),
                ('offer_expiration', models.DurationField(default=datetime.timedelta(days=3))),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
