# Generated by Django 5.2.4 on 2025-07-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('working', 'Working'), ('rejected', 'Rejected'), ('offer_expired', 'Offer Expired'), ('auto_rejected', 'Auto Rejected'), ('declined', 'Declined')], default='applied', max_length=20),
        ),
    ]
