# Generated by Django 5.2.4 on 2025-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
