# Generated by Django 5.2.4 on 2025-10-24 05:05

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), applications.models.validate_resume_size]),
        ),
    ]
